class COLUMN:
    N_CMD_START = "n_start_cmd"
    N_CMD_REGISTR = "n_reg_cmd"
    N_CMD_TEXTME = "n_txtAdmin_cmd"
    UNKNOWN = "n_unkwn_cmd"
    NAME = "first_name"
    LAST_NAME = "last_name"
    USERNAME = "telegram_username"
    TELEGRAM_ID = "telegram_id"
    DISP_GIORNO = "giorno"
    DISP_FASCIA = "fascia"