# Generated by Django 5.1.3 on 2025-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disponibilita",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("telegram_id", models.BigIntegerField()),
                ("giorno", models.DateField(blank=True, null=True)),
                ("fascia", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nome_cognome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "disponibilita",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Volontari",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("n_start_cmd", models.IntegerField(default=0)),
                ("n_reg_cmd", models.IntegerField(default=0)),
                ("n_unkwn_cmd", models.IntegerField(default=0)),
                ("n_txtAdmin_cmd", models.IntegerField(default=0)),
                ("n_disp_cmd", models.IntegerField(default=0)),
                ("n_myshift_cmd", models.IntegerField(default=0)),
                ("n_allshift_cmd", models.IntegerField(default=0)),
                ("n_cmdlist_cmd", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "volontari",
                "managed": False,
            },
        ),
    ]
